version: "3.1"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        IS_TEST: 1
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
    environment:
      - POSTGRES_USER=${DB_USER_TEST}
      - POSTGRES_PASSWORD=${DB_PASS_TEST}
      - POSTGRES_DB=${DB_NAME_TEST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - IS_TEST=1
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${DB_USER_TEST}
      - POSTGRES_PASSWORD=${DB_PASS_TEST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${DB_NAME_TEST}