"""Cities name unique

Revision ID: 1761300297b8
Revises: 64a3690a3b9b
Create Date: 2024-04-16 00:10:25.895045

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1761300297b8"
down_revision: Union[str, None] = "64a3690a3b9b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "cities", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "cities", type_="unique")
    # ### end Alembic commands ###
